Build configuration changed. Regenerating backend.
Traceback (most recent call last):
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/build/gen_test_backend.py", line 39, in <module>
    sys.exit(gen_test_backend())
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/build/gen_test_backend.py", line 35, in gen_test_backend
    backend.consume(data)
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/backend/base.py", line 126, in consume
    for obj in objs:
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/frontend/emitter.py", line 182, in emit
    objs = list(emitfn(out))
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/frontend/emitter.py", line 1219, in _process_test_manifests
    for obj in self._process_test_manifest(context, info, path, manifest):
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/frontend/emitter.py", line 1335, in _process_test_manifest
    context)
mozbuild.frontend.reader.SandboxValidationError:
==============================
ERROR PROCESSING MOZBUILD FILE
==============================

The error occurred while processing the following file or one of the files it includes:

    /Users/jlaster/src/mozilla/debugger.html/firefox/devtools/client/debugger/moz.build

The error occurred when validating the result of the execution. The reported error is:

    Error processing test manifest file /Users/jlaster/src/mozilla/debugger.html/firefox/devtools/client/debugger/new/test/mochitest/browser.ini: Traceback (most recent call last):

      File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/frontend/emitter.py", line 1264, in _process_test_manifest
        path, ', '.join(missing)), context)

    SandboxValidationError:
    ==============================
    ERROR PROCESSING MOZBUILD FILE
    ==============================

    The error occurred while processing the following file or one of the files it includes:

        /Users/jlaster/src/mozilla/debugger.html/firefox/devtools/client/debugger/moz.build

    The error occurred when validating the result of the execution. The reported error is:

        Test manifest (/Users/jlaster/src/mozilla/debugger.html/firefox/devtools/client/debugger/new/test/mochitest/browser.ini) lists test that does not exist: browser_dbg-expressions-error.js




make: *** [backend.TestManifestBackend] Error 1
Error running mach:

    ['mochitest', 'devtools/client/debugger/new']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

Exception: Process executed with non-0 exit code 2: [u'/usr/bin/make', u'-f', u'/Users/jlaster/src/mozilla/debugger.html/firefox/build/rebuild-backend.mk', u'-j8', u'-s', u'backend.TestManifestBackend']

  File "/Users/jlaster/src/mozilla/debugger.html/firefox/testing/mochitest/mach_commands.py", line 312, in run_mochitest_general
    tests = mochitest.resolve_tests(test_paths, test_objects, cwd=self._mach_context.cwd)
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/testing/mochitest/mach_commands.py", line 111, in resolve_tests
    resolver = self._spawn(TestResolver)
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/base.py", line 727, in _spawn
    topobjdir=self.topobjdir)
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/testing.py", line 195, in __init__
    self.topsrcdir, 'build', 'gen_test_backend.py'),
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/base.py", line 655, in _run_make
    return fn(**params)
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mozbuild/mozbuild/base.py", line 710, in _run_command_in_objdir
    return self.run_process(cwd=self.topobjdir, **args)
  File "/Users/jlaster/src/mozilla/debugger.html/firefox/python/mach/mach/mixin/process.py", line 147, in run_process
    raise Exception('Process executed with non-0 exit code %d: %s' % (status, args))
